djcostcenter/apps/flow/urls.py
from django.conf.urls import url
from .views import Dashboard, AccountList, AccountNew, AccountDelete, AccountEdit
from .views import TransactionList, TransactionNew, TransactionEdit, TransactionDelete
from .views import CategoryList, CategoryNew, CategoryEdit, CategoryDelete
from .views import TransactionCommentList, TransactionCommentNew
from .views import CostCenterList, CostCenterNew, CostCenterDelete, CostCenterEdit

app_name = 'flow'

urlpatterns = [
    url(r'dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'flow/account/list/$', AccountList.as_view(), name="account-list"),
    url(r'flow/account/new/$', AccountNew.as_view(), name="account-new"),
    url(r'flow/account/delete/(?P<pk>.*)/$', AccountDelete.as_view(), name="account-delete"),
    url(r'flow/account/edit/(?P<pk>.*)/$', AccountEdit.as_view(), name="account-edit"),
    url(r'flow/transaction/list/$', TransactionList.as_view(), name="transaction-list"),
    url(r'flow/transaction/new/$', TransactionNew.as_view(), name="transaction-new"),
    url(r'flow/transaction/edit/(?P<pk>.*)/$', TransactionEdit.as_view(), name="transaction-edit"),
    url(r'flow/transaction/delete/(?P<pk>.*)/$', TransactionDelete.as_view(), name="transaction-delete"),
    url(r'flow/category/list/$', CategoryList.as_view(), name="category-list"),
    url(r'flow/category/new/$', CategoryNew.as_view(), name="category-new"),
    url(r'flow/category/edit/(?P<pk>.*)/$', CategoryEdit.as_view(), name="category-edit"),
    url(r'flow/category/delete/(?P<pk>.*)/$', CategoryDelete.as_view(), name="category-delete"),
    url(r'flow/transaction/comment/list/$', TransactionCommentList.as_view(), name="transaction-comment-list"),
    url(r'flow/transaction/(?P<trans_id>.*)/comment/new/$', TransactionCommentNew.as_view(), name="transaction-comment-new"),
    url(r'flow/cost_center/list/$', CostCenterList.as_view(), name="cost_center-list"),
    url(r'flow/cost_center/new/$', CostCenterNew.as_view(), name="cost_center-new"),
    url(r'flow/cost_center/edit/(?P<pk>.*)/$', CostCenterEdit.as_view(), name="cost_center-edit"),
    url(r'flow/cost_center/delete/(?P<pk>.*)/$', CostCenterDelete.as_view(), name="cost_center-delete"),
]

djcostcenter/apps/security/urls.py
from django.conf.urls import url
from .views import Login, Logout
from .views import UserProfileData, UserList, UserNew, UserDelete
from .views import ActiveInactiveUser, ChangePassword

app_name = 'security'

urlpatterns = [
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', Logout.as_view(), name="logout"),
    url(r'^userprofile/$', UserProfileData.as_view(), name="userprofile"),
    url(r'^userprofilechange-password/$', ChangePassword.as_view(), name="userprofile-change-password"),
    url(r'^user/list/$', UserList.as_view(), name="user-list"),
    url(r'^user/new/$', UserNew.as_view(), name="user-new"),
    url(r'^user/delete/(?P<pk>.*)/$', UserDelete.as_view(), name="user-delete"),
    url(r'^user/active-inactive/(?P<user_id>.*)/$', ActiveInactiveUser.as_view(), name="user-active-inactive"),
]

djcostcenter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from djcostcenter.core.json_settings import get_settings

settings_json = get_settings()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djcostcenter.apps.website.urls')),
    url(r'^flow/', include('djcostcenter.apps.flow.urls')),
    url(r'^security/', include('djcostcenter.apps.security.urls'))
]

if settings_json["DEBUG"]:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djcostcenter/apps/security/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone


class UserProfile(models.Model):

    def image_path(self, filename):
        extension = os.path.splitext(filename)[1][1:]
        file_name = os.path.splitext(filename)[0]
        url = "Users/%s/profile/%s.%s" % (self.user.id, slugify(str(file_name)), extension)
        return url

    user = models.OneToOneField(User)
    image_profile = models.ImageField(upload_to=image_path, null=True, blank=True)

    def __str__(self):
        return self.user.get_full_name()


# ============================================================
# Conectamos signals.
# ============================================================

from .signals import *

djcostcenter/apps/security/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):

    email = forms.CharField(widget=forms.EmailInput(attrs=({'class': 'validate'})), required=True)
    password = forms.CharField(widget=forms.PasswordInput(render_value=False, attrs=({'class': 'validate'})), required=True)
    my_user = None  # Si se logea un usuario correctamente entonces se almacena aqui la sesion.

    def clean_password(self):
        from django.contrib.auth import authenticate
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except:
            user = None
        if user:
            user_auth = authenticate(username=user.username, password=self.cleaned_data['password'])
        else:
            user_auth = None
        if user_auth is not None:
            if user.is_active:
                self.my_user = user_auth
                pass
            else:
                raise forms.ValidationError("Lo lamentamos, el usuario se encuentra deshabilitado")
        else:
            raise forms.ValidationError("Email y/o contraseña incorrecta")


class RecoverPasswordForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs=({'class': 'validate form-control',
                                                            'placeholder': 'Ingresa tu mail'})),
                            required=True, label="")


class ChangePasswordForm(forms.Form):
    password_one = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'validate form-control',
                                                                      'placeholder': 'Nueva contraseña',
                                                                      'required': 'required'})),
                                   required=True, label="")
    password_two = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'validate form-control',
                                                                      'placeholder': 'Repite tu nueva contraseña',
                                                                      'required': 'required'})),
                                   required=True, label="")

    def clean_password_two(self):
        if self.cleaned_data['password_one'] == self.cleaned_data['password_two']:
            pass
        else:
            raise forms.ValidationError("Contraseñas no coinciden, intente de nuevo.")


class NewTokenForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs=({'class': 'validate form-control',
                                                            'placeholder': 'Ingresa tu mail'})),
                            required=True, label="")


class RegisterForm(forms.Form):

    first_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control',
                                                                 'placeholder': 'Nombre','required':'required','autofocus':'autofocus'})),
                                 required=True, label="")
    last_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control',
                                                                'placeholder': 'Apellido','required':'required'})),
                                required=True, label="")
    email = forms.EmailField(widget=forms.EmailInput(attrs=({'class': 'form-control', 'required': 'true',
                                                            'placeholder': 'Email','required':'required'})),
                             required=True, label="")
    password_one = forms.CharField(widget=forms.PasswordInput(render_value=False,
                                                              attrs=({'class': 'form-control',
                                                                      'placeholder': 'Contraseña','required':'required'})),
                                   required=True, label="")
    password_two = forms.CharField(widget=forms.PasswordInput(render_value=False,
                                                              attrs=({'class': 'form-control',
                                                                      'placeholder': 'Repite de nuevo tu contraseña ','required':'required'})),
                                   required=True, label="")

    def clean_email(self):
        try:
            User.objects.get(email=self.cleaned_data['email'])
            raise forms.ValidationError("Este email ya se encuentra registrado, has perdido tu contraseña?")
        except User.DoesNotExist:
            return self.cleaned_data['email']

    def clean_password_two(self):
        if self.cleaned_data['password_one'] == self.cleaned_data['password_two']:
            pass
        else:
            raise forms.ValidationError("Contraseña no coincide, intente de nuevo")

djcostcenter/apps/security/views.py
import random, string
from django.template.loader import render_to_string
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import View, ListView, DeleteView
from django.shortcuts import render
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.contrib import messages
from .forms import LoginForm
from .models import UserProfile
from .functions import SecurityUtils
from djcostcenter.apps.general_functions import send_email
from djcostcenter.core.json_settings import get_settings
from djcostcenter.apps import response_messages

settings = get_settings()


class Login(View):
    template_name = "login.html"
    form = LoginForm

    def get(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('flow:dashboard'))
        else:
            ctx = {'form': self.form}
            if 'next' in request.GET:
                ctx['next'] = request.GET['next']
            return render(request, self.template_name, ctx)

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            login(request, form.my_user)
            messages.success(request, _("Bienvenido {0}!".format(form.my_user.first_name)))
            if 'next' in request.POST:
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse_lazy('flow:dashboard'))
        else:
            ctx = {'form': form}
            return render(request, self.template_name, ctx)


class Logout(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('website:index'))


class UserProfileData(LoginRequiredMixin, View):
    template_name = "userprofile.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        userprofile = request.user.userprofile
        image_profile = request.FILES['image_profile'] if 'image_profile' in request.FILES else None
        if image_profile:
            userprofile.image_profile = image_profile
            userprofile.save()
        request.user.username = request.POST['email']
        request.user.first_name = request.POST['first_name']
        request.user.last_name = request.POST['last_name']
        request.user.email = request.POST['email']
        request.user.save()
        return HttpResponseRedirect(reverse_lazy('flow:dashboard'))


class ChangePassword(LoginRequiredMixin, View):
    template_name = "change_password.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        password_one = request.POST['password_one'] if 'password_one' in request.POST else None
        password_two = request.POST['password_two'] if 'password_two' in request.POST else None
        if password_one and password_two:
            if password_one == password_two:
                request.user.set_password(password_one)
                request.user.save()
                logout(request)
                return HttpResponseRedirect(reverse_lazy('security:login'))
            else:
                messages.error(request, _("Las contraseñas no coinciden"))
        else:
            messages.error(request, _("Error en los datos recibidos"))
        return self.get(request)


class UserList(LoginRequiredMixin, ListView):
    template_name = "user_list.html"
    model = UserProfile
    paginate_by = 10


class UserDelete(LoginRequiredMixin, DeleteView):
    template_name = "user_delete.html"
    model = UserProfile
    success_url = reverse_lazy('security:user-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(UserDelete, self).delete(request, *args, **kwargs)


class UserNew(LoginRequiredMixin, View):
    template_name = "user_new.html"
    utils = SecurityUtils()

    def send_welcome_mail(self, request, new_user, new_user_password):
        ctx = {'user': request.user, 'new_user': new_user, 'new_user_password': new_user_password, 'URL_SERVER': settings['URL_SERVER']}
        html_content = render_to_string('mailing/welcome.html', ctx)
        subject = _("Bienvenido a DjCostCenter / invitacion")
        send_email(subject, to_email=new_user.email, html_content=html_content)

    def get(self, request):
        ctx = {'random_password': self.utils.random_password()}
        return render(request, self.template_name, ctx)

    def post(self, request):
        try:
            user_exist = User.objects.get(email=request.POST['email'])
        except:
            user_exist = None
        if user_exist:
            messages.error(request, _("Email {0} ya se encuentra registrado en el sistema".format(request.POST['email'])))
            ctx = {'random_password': self.utils.random_password(), 'first_name': request.POST['first_name'],
                   'last_name': request.POST['last_name'], 'email': request.POST['email']}
            return render(request, self.template_name, ctx)
        else:
            new_user = User.objects.create_user(request.POST['email'],
                                                request.POST['email'],
                                                request.POST['password'])
            new_user.first_name = request.POST['first_name']
            new_user.last_name = request.POST['last_name']
            new_user.is_active = True  # Activamos al usuario
            new_user.save()
            # Enviamos un email de bienvenida
            self.send_welcome_mail(request, new_user, request.POST['password'])
            messages.success(request, response_messages.SAVE_SUCCESSFULL)
            return HttpResponseRedirect(reverse_lazy('security:user-list'))


class ActiveInactiveUser(LoginRequiredMixin, View):
    """
    Activamos / Desactivamos usuarios.
    """

    def get(self, request, user_id):
        try:
            user = User.objects.get(id=user_id)
            user.is_active = not user.is_active
            user.save()
            messages.success(request, response_messages.UPDATE_SUCCESSFULL)
        except User.DoesNotExist:
            messages.error(request, _("Usuario no encontrado"))
        return HttpResponseRedirect(reverse_lazy('security:user-list'))

djcostcenter/apps/security/templates/change_password.html
{% extends 'base.html' %}
{% load i18n static add_class %}
{% block title %}{% trans 'Perfil' %}{% endblock %}
{% block page-title %}{% trans 'Cambiar contraseña' %}{% endblock %}
{% block nav_cuentas %}active{% endblock %}
{% block content %}
    <div class="alert alert-warning" role="alert">
        {% trans 'Al realizar el cambio de contraseña, el sistema eliminará su sesión activa y por su seguridad, pedirá que ingrese de nuevo sus credenciales en la ventana de acceso a DjCostCenter.' %}
    </div>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_password_one">{% trans 'Ingrese nueva contraseña' %}</label>
                    <input autofocus id="id_password_one" type="password" name="password_one" class="form-control">
                </div>
            </div>
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_password_two">{% trans 'Repita la contraseña' %}</label>
                    <input id="id_password_two" type="password" name="password_two" class="form-control">
                </div>
            </div>
        </div>
        <div class="text-right">
            <a href="{% url 'security:userprofile' %}" class="btn btn-default">{% trans 'Regresar' %}</a>
            <input class="btn btn-primary" type="submit" value="{% trans 'Cambiar contraseña' %}">
        </div>
    </form>
{% endblock content %}

djcostcenter/apps/security/templates/login.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Inicio de sesión' %}</title>
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="container">
    <form class="form-signin" method="post" action=".">

             <img src="{% static 'img/cashflow.png' %}" class="img-responsive" style="display: block;margin: auto" alt="">
             <h2 class="form-signin-heading text-center">{% trans 'Ingresar' %}</h2>

        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        <!-- Email -->
        <label for="{{ form.email.id }}"> {{ form.email.label }}</label><br>
        <input type="email" name="email" id="id_email" class="form-control" placeholder="{% trans 'Email' %}">
        {% if form.email.errors %}
            {% for error  in form.email.errors %}
                <div>
                    <small>{{ error }}</small>
                </div>
            {% endfor %}
        {% endif %}
        <!-- Finaliza Email -->
        <!-- Password -->
        <label for="{{ form.password.id }}"> {{ form.password.label }}</label><br>
        <input type="password" name="password" class="form-control" id="id_password"
               placeholder="{% trans 'Contraseña' %}">
        {% if form.password.errors %}
            {% for error  in form.password.errors %}
                <div>
                    <small>{{ error }}</small>
                </div>
            {% endfor %}
        {% endif %}
        <!-- Fin Password -->
        <button class="btn btn-primary btn-block" type="submit">{% trans 'Ingresar' %}</button>
        <a href="/" class="btn-link pull-right"><small>{% trans 'Regresar' %}</small></a>
    </form>
</div> <!-- /container -->

<script src="{% static 'libs/jquery/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'libs/popper/popper.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

djcostcenter/apps/security/templates/user_delete.html
{% extends 'base.html' %}
{% load i18n static add_class %}
{% block title %}{% trans 'Eliminar usuario' %}{% endblock %}
{% block page-title %}{% trans 'Eliminar usuario' %}{% endblock %}
{% block nav_users %}active{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h3 class="text-center">{% trans '¿Seguro que deseas eliminar este elemento?' %}</h3>
        <form action="." method="post">
            {% csrf_token %}

            <p class="text-center">
                <a href="{% url 'security:user-list' %}" class="btn btn-secondary">{% trans 'Regresar' %}</a>
                <input class="btn btn-danger" type="submit" value="{% trans 'Eliminar' %}">
            </p>

        </form>
    </div>
{% endblock content %}

djcostcenter/apps/security/templates/user_list.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% trans 'Usuarios' %}{% endblock %}
{% block page-title %}{% trans 'Usuarios' %}{% endblock %}
{% block nav_users %}active{% endblock %}
{% block add-button %}
     <a href="{% url 'security:user-new' %}" class="btn btn-outline-primary"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>
{% endblock %}
{% block content %}
    <table class="table table-sm">
        <thead class="thead-inverse text-center">
            <tr>
                <th width="30%" align="center">{% trans 'Email' %}</th>
                <th width="15%" align="center">{% trans 'Nombre(s)' %}</th>
                <th width="15%" align="center">{% trans 'Apellido(s)' %}</th>
                <th width="15%" align="center">{% trans 'Activo' %}</th>
                <th width="5%"></th>
            </tr>
        </thead>
        <tbody>
        {% for element in object_list %}
            <tr>
                <td>{{ element.user.email }} {% if user == element.user %}({% trans 'Yo' %}){% endif %}</td>
                <td>{{ element.user.first_name }}</td>
                <td>{{ element.user.last_name }}</td>
                <td>
                {% if user != element.user %}
                <a href="{% url 'security:user-active-inactive' element.user.id %}">
                    {% if element.user.is_active %}
                        <i class="fa fa-toggle-on fa-2x text-success"></i>
                    {% else %}
                        <i class="fa fa-toggle-off fa-2x text-secondary"></i>
                    {% endif %}
                </a>
                {% else %}
                    <i class="fa fa-toggle-on fa-2x text-success"></i>
                {% endif %}
                </td>
                <td><a {% if user == element.user %}disabled{% endif %} href="{% if user != element.user %}{% url 'security:user-delete' element.pk %}{% else %}#{% endif %}" class="btn {% if user != element.user %}btn-danger{% else %} btn-secondary {% endif %} btn-sm"><i class="fa fa-trash"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'includes/paginator.html' with url_list='/security/transaction/list/' %}
{% endblock content %}

djcostcenter/apps/security/templates/user_new.html
{% extends 'base.html' %}
{% load i18n static add_class %}
{% block title %}{% trans 'Usuarios' %}{% endblock %}
{% block page-title %}{% trans 'Nuevo usuario' %}{% endblock %}
{% block nav_users %}active{% endblock %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_first_name">{% trans 'Nombre(s)' %}</label>
                    <input id="id_first_name" name="first_name" class="form-control" autofocus required {% if last_name %}value="{{ last_name }}" {% endif %}>
                </div>
            </div>
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_last_name">{% trans 'Apellido(s)' %}</label>
                    <input id="id_last_name" name="last_name" class="form-control" required {% if first_name %}value="{{ first_name }}" {% endif %}>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_email">{% trans 'Correo electrónico' %}</label>
                    <input id="id_email" name="email" type="email" class="form-control" {% if email %}value="{{ email }}" {% endif %}
                           required>
                </div>
            </div>
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_password">{% trans 'Contraseña' %}</label>
                    <input id="id_password" name="password" required value="{{ random_password }}"
                           class="form-control">
                </div>
            </div>
        </div>
    <div class="text-right">
        <a href="{% url 'security:user-list' %}" class="btn btn-secondary">{% trans 'Regresar' %}</a>
        <input class="btn btn-outline-primary" type="submit" value="{% trans 'Guardar' %}">
    </div>
    </form>
{% endblock content %}

djcostcenter/apps/security/templates/userprofile.html
{% extends 'base.html' %}
{% load i18n static add_class %}
{% block title %}{% trans 'Perfil' %}{% endblock %}
{% block page-title %}{% trans 'Perfil de usuario' %}{% endblock %}
{% block nav_cuentas %}active{% endblock %}
{% block content %}
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_first_name">{% trans 'Nombre(s)' %}</label>
                    <input id="id_first_name" value="{{ user.first_name }}" name="first_name" class="form-control">
                </div>
            </div>
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_last_name">{% trans 'Apellido(s)' %}</label>
                    <input id="id_last_name" value="{{ user.last_name }}" name="last_name" class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_email">{% trans 'Correo electrónico' %}</label>
                    <input id="id_email" name="email" type="email" value="{{ user.email }}" class="form-control"
                           required>
                </div>
            </div>
            <div class="col-xs-6 col-md-6">
                <div class="form-group">
                    <label for="id_image_profile">{% trans 'Imagen de perfil' %}</label>
                    <input id="id_image_profile" type="file" value="{{ user.first_name }}" name="image_profile"
                           class="form-control">
                    {% if user.userprofile.image_profile %}
                        <small><a target="_blank"
                                  href="{{ user.userprofile.image_profile.url }}">{% trans 'Ver actual' %}</a></small>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="text-right">
            <a href="{% url 'security:userprofile-change-password' %}" class="btn btn-secondary pull-left"><i class="fa fa-key"></i> {% trans 'Cambiar contraseña' %}</a>
            <a href="{% url 'flow:dashboard' %}" class="btn btn-default">{% trans 'Regresar' %}</a>
            <input class="btn btn-primary" type="submit" value="{% trans 'Guardar' %}">
        </div>
    </form>
{% endblock content %}