djcostcenter/apps/security/urls.py
from django.conf.urls import url
from .views import Login, Logout
from .views import UserProfileData, UserList, UserNew, UserDelete
from .views import ActiveInactiveUser, ChangePassword

app_name = 'security'

urlpatterns = [
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', Logout.as_view(), name="logout"),
    url(r'^userprofile/$', UserProfileData.as_view(), name="userprofile"),
    url(r'^userprofilechange-password/$', ChangePassword.as_view(), name="userprofile-change-password"),
    url(r'^user/list/$', UserList.as_view(), name="user-list"),
    url(r'^user/new/$', UserNew.as_view(), name="user-new"),
    url(r'^user/delete/(?P<pk>.*)/$', UserDelete.as_view(), name="user-delete"),
    url(r'^user/active-inactive/(?P<user_id>.*)/$', ActiveInactiveUser.as_view(), name="user-active-inactive"),
]

djcostcenter/apps/website/urls.py
from django.conf.urls import url
from .views import Index

app_name = 'website'

urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
]

djcostcenter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from djcostcenter.core.json_settings import get_settings

settings_json = get_settings()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djcostcenter.apps.website.urls')),
    url(r'^flow/', include('djcostcenter.apps.flow.urls')),
    url(r'^security/', include('djcostcenter.apps.security.urls'))
]

if settings_json["DEBUG"]:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djcostcenter/apps/website/models.py
from django.db import models
from django.utils.translation import ugettext as _

from solo.models import SingletonModel


class SiteConfiguration(SingletonModel):
    site_name = models.CharField(max_length=255, default='djcostcenter')

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = _("Configuración del sitio")

djcostcenter/apps/website/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = "index.html"

djcostcenter/apps/website/templates/index.html
{% load i18n static solo_tags %}
{% get_solo 'website.SiteConfiguration' as site_config %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>{{ site_config.site_name }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>

<body>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">{{ site_config.site_name }}</h3>
                    <nav class="nav nav-masthead">
                        <a class="nav-link active" href="{% url 'security:login' %}">{% trans 'Ingresar' %}</a>
{#                        <a class="nav-link" href="#">Características</a>#}
{#                        <a class="nav-link" href="#">Contactos</a>#}
                    </nav>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">DjCostCenter</h1>
                <p class="lead">{% trans 'Maneje de forma efectiva el flujo de de ingresos y egresos que tiene su negocio o personal' %}</p>
                <p class="lead">
{#                    <a href="#" class="btn btn-lg btn-secondary">Aprenda más</a>#}
                </p>
            </div>
            <div class="mastfoot">
                <div class="inner">
                    <p>Impulsado por <a href="https://bitbucket.com/adlpaf/djcostcenter"> Aplicación Open Source</a>, escrito por <a
                            href="https://twitter.com/adlpaf/">@adlpaf</a>.</p>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'libs/jquery/jquery-1.12.4.js' %}"></script>
<script src="{% static 'libs/popper/popper.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'libs/ie10/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>